In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('data_clean.csv')

In [3]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",http://toystory.disney.com/toy-story
1,710,GoldenEye,James Bond must unmask the mysterious head of ...,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,Craig and Smokey are two guys in Los Angeles h...,"[{'id': 35, 'name': 'Comedy'}]","[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",http://www.newline.com/properties/friday.html

In [4]:
import ast

In [5]:
def genres(col):
    l=[]
    for i in ast.literal_eval(col):
        l.append(i['name']) 
    return l

In [7]:
data['genres']=data['genres'].apply(genres)

In [8]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",http://toystory.disney.com/toy-story
1,710,GoldenEye,James Bond must unmask the mysterious head of ...,"[Adventure, Action, Thriller]","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,Craig and Smokey are two guys in Los Angeles h...,[Comedy],"[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",http://www.newline.com/properties/friday.html

In [12]:
data['overview']=data['overview'].apply(lambda x:x.split())

In [13]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],"[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",http://www.newline.com/properties/friday.html

In [16]:
print(data['genres'].iloc[0])
print(type(data['genres'].iloc[0]))

['Animation', 'Comedy', 'Family']
<class 'list'>

In [17]:
data['genres'] = data['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [25]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]","[PierceBrosnan, SeanBean, IzabellaScorupco, Fa...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],"[IceCube, ChrisTucker, NiaLong, TomListerJr., ...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://www.newline.com/properties/friday.html

In [18]:
print(data['cast'].iloc[0])
print(type(data['cast'].iloc[0]))

['TomHanks', 'TimAllen', 'DonRickles', 'JimVarney', 'WallaceShawn', 'JohnRatzenberger', 'AnniePotts', 'JohnMorris', 'ErikvonDetten', 'LaurieMetcalf', 'R.LeeErmey', 'SarahFreeman', 'PennJillette']
<class 'list'>

In [20]:
data['cast'] = data['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [24]:
print(data['crew'].iloc[0])
print(type(data['crew'].iloc[0]))

['[', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '4', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'D', 'i', 'r', 'e', 'c', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '7', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'h', 'n', '', 'L', 'a', 's', 's', 'e', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', '7', 'E', 'd', 'q', 'i', 'N', 'b', 'r', '4', 'F', 'R', 'j', 'I', 'h', 'K', 'H', 'y', 'P', 'P', 'd', 'F', 'f', 'E', 'E', 'E', 'F', 'G', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '4', 'f', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 's', 's', '', 'W', 'h', 'e', 'd', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'd', 'T', 'i', 'V', 's', 'u', 'a', 'T', 'V', 'T', 'e', 'G', 'm', 'v', 'k', 'h', 'c', 'y', 'J', 'v', 'K', 'p', '2', 'A', '5', 'k', 'r', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '5', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'A', 'n', 'd', 'r', 'e', 'w', '', 'S', 't', 'a', 'n', 't', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'p', 'v', 'Q', 'W', 's', 'u', '0', 'q', 'c', '8', 'J', 'F', 'Q', 'h', 'M', 'V', 'J', 'k', 'T', 'H', 'u', 'e', 'x', 'U', 'A', 'a', '1', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '5', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '2', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'e', 'l', '', 'C', 'o', 'h', 'e', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'd', 'A', 'u', 'b', 'A', 'i', 'Z', 'c', 'v', 'K', 'F', 'b', 'b', 'o', 'W', 'l', 'j', '7', 'o', 'X', 'O', 'k', 'Z', 'n', 'T', 'S', 'u', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', '1', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'A', 'l', 'e', 'c', '', 'S', 'o', 'k', 'o', 'l', 'o', 'w', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'v', '7', '9', 'v', 'l', 'R', 'Y', 'i', '9', '4', 'B', 'Z', 'U', 'Q', 'n', 'k', 'k', 'y', 'z', 'n', 'b', 'G', 'U', 'Z', 'L', 'j', 'T', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', '7', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '1', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '4', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'B', 'o', 'n', 'n', 'i', 'e', '', 'A', 'r', 'n', 'o', 'l', 'd', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', 'd', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '5', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'x', 'e', 'c', 'u', 't', 'i', 'v', 'e', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'E', 'd', '', 'C', 'a', 't', 'm', 'u', 'l', 'l', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '7', '3', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '6', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'l', 'p', 'h', '', 'G', 'u', 'g', 'g', 'e', 'n', 'h', 'e', 'i', 'm', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '7', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '7', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'x', 'e', 'c', 'u', 't', 'i', 'v', 'e', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'S', 't', 'e', 'v', 'e', '', 'J', 'o', 'b', 's', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'm', 'O', 'M', 'P', '3', 'S', 'w', 'D', '5', 'q', 'W', 'Q', 'S', 'R', '0', 'l', 'd', 'C', 'I', 'B', 'y', 'd', '3', 'g', 'u', 'T', 'V', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '8', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '8', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'L', 'e', 'e', '', 'U', 'n', 'k', 'r', 'i', 'c', 'h', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'b', 'd', 'T', 'C', 'C', 'X', 'j', 'g', 'O', 'V', '3', 'Y', 'y', 'a', 'N', 'm', 'L', 'G', 'Y', 'G', 'O', 'x', 'F', 'Q', 'M', 'O', 'c', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '9', '1', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'A', 'r', 't', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '8', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'l', 'p', 'h', '', 'E', 'g', 'g', 'l', 'e', 's', 't', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'u', 'U', 'f', 'c', 'G', 'K', 'D', 's', 'K', 'O', '1', 'a', 'R', 'O', 'M', 'p', 'X', 'R', 's', '6', '7', 'H', 'n', '6', 'R', 'v', 'R', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '9', '8', '3', '3', '1', 'b', 'f', '9', '2', '5', '1', '4', '1', '4', '2', '1', '2', '0', '1', '0', '4', '4', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '1', '6', '8', '8', '7', '0', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'o', 'b', 'e', 'r', 't', '', 'G', 'o', 'r', 'd', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '6', '8', 'c', 'c', '3', 'a', '3', '6', '8', '0', '9', '6', '6', '0', '0', '9', '5', 'f', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '5', '5', '2', '8', '8', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'F', 'o', 'l', 'e', 'y', '', 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'M', 'a', 'r', 'y', '', 'H', 'e', 'l', 'e', 'n', '', 'L', 'e', 'a', 's', 'm', 'a', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '5', '3', '1', '8', '2', '4', 'd', '9', '2', '5', '1', '4', '1', '5', '2', '8', '9', '0', '0', '0', '9', '4', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '5', '3', '5', '1', '4', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'n', 'i', 'm', 'a', 't', 'i', 'o', 'n', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'K', 'i', 'm', '', 'B', 'l', 'a', 'n', 'c', 'h', 'e', 't', 't', 'e', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '5', '9', '6', '9', '2', '5', '1', '4', '1', '2', 'd', 'c', 'b', '0', '0', '9', 'b', 'f', '6', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '1', '4', '1', '8', '2', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'D', 'R', '', 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'M', 'a', 'r', 'i', 'l', 'y', 'n', '', 'M', 'c', 'C', 'o', 'p', 'p', 'e', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '7', '0', '9', '9', '2', '5', '1', '4', '1', '2', 'd', 'c', '5', '0', '0', 'a', '0', '1', '8', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '8', '5', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'c', 'h', 'e', 's', 't', 'r', 'a', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'n', 'd', 'y', '', 'N', 'e', 'w', 'm', 'a', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'w', '0', 'J', 'z', 'f', 'o', 'i', 'M', '2', '5', 'n', 'r', 'n', 'x', 'Y', 'O', 'z', 'o', 's', 'P', 'H', 'R', 'q', '6', 'm', 'l', 'E', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '6', '9', '3', 'e', '6', 'b', '2', '9', '2', '5', '1', '4', '1', '7', 'b', '0', 'e', '0', '0', '0', '0', 'e', '3', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '2', '9', '5', '4', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'C', 'o', 'l', 'o', 'r', '', 'T', 'i', 'm', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'D', 'a', 'l', 'e', '', 'E', '.', '', 'G', 'r', 'a', 'h', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '2', 'e', '2', '5', '2', '2', 'c', '3', 'a', '3', '6', '8', '6', '9', 'e', '6', '0', '0', '1', 'a', '9', 'c', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '4', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'C', 'G', '', 'P', 'a', 'i', 'n', 't', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'o', 'b', 'i', 'n', '', 'C', 'o', 'o', 'p', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '3', '0', '9', '2', '5', '1', '4', '1', '5', 'c', 'a', '1', '0', '0', '0', '0', '1', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '7', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'h', 'n', '', 'L', 'a', 's', 's', 'e', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', '7', 'E', 'd', 'q', 'i', 'N', 'b', 'r', '4', 'F', 'R', 'j', 'I', 'h', 'K', 'H', 'y', 'P', 'P', 'd', 'F', 'f', 'E', 'E', 'E', 'F', 'G', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '4', '0', 'c', '3', 'a', '3', '6', '8', '2', 'e', '7', '3', '0', '0', '0', '0', '1', 'c', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '0', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'P', 'e', 't', 'e', '', 'D', 'o', 'c', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'r', '6', 'n', 'g', 'P', 'g', 'n', 'R', 'e', 'A', '3', 'R', 'H', 'm', 'K', 'j', 'm', 'S', 'o', 'V', 's', 'c', '6', 'A', 'w', 'j', 'p', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '5', '1', '9', '2', '5', '1', '4', '1', '5', 'c', '9', '2', '0', '0', '0', '0', '1', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '1', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'e', '', 'R', 'a', 'n', 'f', 't', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'f', '1', 'B', 'o', 'W', 'C', '2', 'J', 'b', 'C', 'c', 'f', 'P', '1', 'e', '5', 'h', 'K', 'f', 'G', 's', 'x', 'k', 'H', 'z', 'V', 'U', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', 'c', 'e', 'c', '3', 'a', '3', '6', '8', '2', 'e', '8', '2', '0', '0', '0', '0', '2', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'C', 'r', 'e', 'w', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '6', '2', '9', '4', '1', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'o', 's', 't', '', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '', 'S', 'u', 'p', 'e', 'r', 'v', 'i', 's', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'P', 'a', 't', 's', 'y', '', 'B', 'o', 'u', 'g', 'e', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '4', 'f', '1', '9', '2', '5', '1', '4', '1', '5', 'c', 'a', '1', '0', '0', '0', '0', '8', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'A', 'r', 't', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '6', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'u', 'l', 'p', 't', 'o', 'r', "'",

In [23]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]","[PierceBrosnan, SeanBean, IzabellaScorupco, Fa...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],"[IceCube, ChrisTucker, NiaLong, TomListerJr., ...","[[, {, ', c, r, e, d, i, t, _, i, d, ', :, , '...",http://www.newline.com/properties/friday.html

In [26]:
def convert(x):
    if isinstance(x, str):
        return ast.literal_eval(x)
    return x

In [27]:
data['crew'] = data['crew'].apply(convert)

In [29]:
print(data['crew'].iloc[0])
print(type(data['crew'].iloc[0]))

['[', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '4', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'D', 'i', 'r', 'e', 'c', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '7', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'h', 'n', '', 'L', 'a', 's', 's', 'e', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', '7', 'E', 'd', 'q', 'i', 'N', 'b', 'r', '4', 'F', 'R', 'j', 'I', 'h', 'K', 'H', 'y', 'P', 'P', 'd', 'F', 'f', 'E', 'E', 'E', 'F', 'G', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '4', 'f', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 's', 's', '', 'W', 'h', 'e', 'd', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'd', 'T', 'i', 'V', 's', 'u', 'a', 'T', 'V', 'T', 'e', 'G', 'm', 'v', 'k', 'h', 'c', 'y', 'J', 'v', 'K', 'p', '2', 'A', '5', 'k', 'r', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '5', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'A', 'n', 'd', 'r', 'e', 'w', '', 'S', 't', 'a', 'n', 't', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'p', 'v', 'Q', 'W', 's', 'u', '0', 'q', 'c', '8', 'J', 'F', 'Q', 'h', 'M', 'V', 'J', 'k', 'T', 'H', 'u', 'e', 'x', 'U', 'A', 'a', '1', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '5', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '2', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'e', 'l', '', 'C', 'o', 'h', 'e', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'd', 'A', 'u', 'b', 'A', 'i', 'Z', 'c', 'v', 'K', 'F', 'b', 'b', 'o', 'W', 'l', 'j', '7', 'o', 'X', 'O', 'k', 'Z', 'n', 'T', 'S', 'u', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', '1', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'A', 'l', 'e', 'c', '', 'S', 'o', 'k', 'o', 'l', 'o', 'w', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'v', '7', '9', 'v', 'l', 'R', 'Y', 'i', '9', '4', 'B', 'Z', 'U', 'Q', 'n', 'k', 'k', 'y', 'z', 'n', 'b', 'G', 'U', 'Z', 'L', 'j', 'T', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', '7', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '1', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '4', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'B', 'o', 'n', 'n', 'i', 'e', '', 'A', 'r', 'n', 'o', 'l', 'd', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '6', 'd', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '5', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'x', 'e', 'c', 'u', 't', 'i', 'v', 'e', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'E', 'd', '', 'C', 'a', 't', 'm', 'u', 'l', 'l', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '7', '3', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '6', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'l', 'p', 'h', '', 'G', 'u', 'g', 'g', 'e', 'n', 'h', 'e', 'i', 'm', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '7', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '7', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'x', 'e', 'c', 'u', 't', 'i', 'v', 'e', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'S', 't', 'e', 'v', 'e', '', 'J', 'o', 'b', 's', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'm', 'O', 'M', 'P', '3', 'S', 'w', 'D', '5', 'q', 'W', 'Q', 'S', 'R', '0', 'l', 'd', 'C', 'I', 'B', 'y', 'd', '3', 'g', 'u', 'T', 'V', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '8', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '8', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'L', 'e', 'e', '', 'U', 'n', 'k', 'r', 'i', 'c', 'h', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'b', 'd', 'T', 'C', 'C', 'X', 'j', 'g', 'O', 'V', '3', 'Y', 'y', 'a', 'N', 'm', 'L', 'G', 'Y', 'G', 'O', 'x', 'F', 'Q', 'M', 'O', 'c', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '2', 'f', 'e', '4', '2', '8', '4', 'c', '3', 'a', '3', '6', '8', '4', '7', 'f', '8', '0', '2', '4', 'f', '9', '1', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'A', 'r', 't', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '8', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'i', 'o', 'n', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'l', 'p', 'h', '', 'E', 'g', 'g', 'l', 'e', 's', 't', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'u', 'U', 'f', 'c', 'G', 'K', 'D', 's', 'K', 'O', '1', 'a', 'R', 'O', 'M', 'p', 'X', 'R', 's', '6', '7', 'H', 'n', '6', 'R', 'v', 'R', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '9', '8', '3', '3', '1', 'b', 'f', '9', '2', '5', '1', '4', '1', '4', '2', '1', '2', '0', '1', '0', '4', '4', 'b', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '1', '6', '8', '8', '7', '0', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'o', 'b', 'e', 'r', 't', '', 'G', 'o', 'r', 'd', 'o', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '6', '8', 'c', 'c', '3', 'a', '3', '6', '8', '0', '9', '6', '6', '0', '0', '9', '5', 'f', '9', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '5', '5', '2', '8', '8', '3', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'F', 'o', 'l', 'e', 'y', '', 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'M', 'a', 'r', 'y', '', 'H', 'e', 'l', 'e', 'n', '', 'L', 'e', 'a', 's', 'm', 'a', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '5', '3', '1', '8', '2', '4', 'd', '9', '2', '5', '1', '4', '1', '5', '2', '8', '9', '0', '0', '0', '9', '4', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '5', '3', '5', '1', '4', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'n', 'i', 'm', 'a', 't', 'i', 'o', 'n', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'K', 'i', 'm', '', 'B', 'l', 'a', 'n', 'c', 'h', 'e', 't', 't', 'e', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '5', '9', '6', '9', '2', '5', '1', '4', '1', '2', 'd', 'c', 'b', '0', '0', '9', 'b', 'f', '6', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '1', '4', '1', '8', '2', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'A', 'D', 'R', '', 'E', 'd', 'i', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'M', 'a', 'r', 'i', 'l', 'y', 'n', '', 'M', 'c', 'C', 'o', 'p', 'p', 'e', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '8', '9', '2', '1', '7', '0', '9', '9', '2', '5', '1', '4', '1', '2', 'd', 'c', '5', '0', '0', 'a', '0', '1', '8', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'S', 'o', 'u', 'n', 'd', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '8', '5', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'c', 'h', 'e', 's', 't', 'r', 'a', 't', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'a', 'n', 'd', 'y', '', 'N', 'e', 'w', 'm', 'a', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'w', '0', 'J', 'z', 'f', 'o', 'i', 'M', '2', '5', 'n', 'r', 'n', 'x', 'Y', 'O', 'z', 'o', 's', 'P', 'H', 'R', 'q', '6', 'm', 'l', 'E', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '6', '9', '3', 'e', '6', 'b', '2', '9', '2', '5', '1', '4', '1', '7', 'b', '0', 'e', '0', '0', '0', '0', 'e', '3', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'E', 'd', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '4', '2', '9', '5', '4', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'C', 'o', 'l', 'o', 'r', '', 'T', 'i', 'm', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'D', 'a', 'l', 'e', '', 'E', '.', '', 'G', 'r', 'a', 'h', 'n', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '2', 'e', '2', '5', '2', '2', 'c', '3', 'a', '3', '6', '8', '6', '9', 'e', '6', '0', '0', '1', 'a', '9', 'c', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '4', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'C', 'G', '', 'P', 'a', 'i', 'n', 't', 'e', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'R', 'o', 'b', 'i', 'n', '', 'C', 'o', 'o', 'p', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '3', '0', '9', '2', '5', '1', '4', '1', '5', 'c', 'a', '1', '0', '0', '0', '0', '1', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '7', '8', '7', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'h', 'n', '', 'L', 'a', 's', 's', 'e', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', '7', 'E', 'd', 'q', 'i', 'N', 'b', 'r', '4', 'F', 'R', 'j', 'I', 'h', 'K', 'H', 'y', 'P', 'P', 'd', 'F', 'f', 'E', 'E', 'E', 'F', 'G', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '4', '0', 'c', '3', 'a', '3', '6', '8', '2', 'e', '7', '3', '0', '0', '0', '0', '1', 'c', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '2', ',', '', "'", 'i', 'd', "'", ':', '', '1', '2', '8', '9', '0', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'P', 'e', 't', 'e', '', 'D', 'o', 'c', 't', 'e', 'r', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'r', '6', 'n', 'g', 'P', 'g', 'n', 'R', 'e', 'A', '3', 'R', 'H', 'm', 'K', 'j', 'm', 'S', 'o', 'V', 's', 'c', '6', 'A', 'w', 'j', 'p', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', '5', '1', '9', '2', '5', '1', '4', '1', '5', 'c', '9', '2', '0', '0', '0', '0', '1', '5', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'W', 'r', 'i', 't', 'i', 'n', 'g', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '1', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'S', 't', 'o', 'r', 'y', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'J', 'o', 'e', '', 'R', 'a', 'n', 'f', 't', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', "'", '/', 'f', '1', 'B', 'o', 'W', 'C', '2', 'J', 'b', 'C', 'c', 'f', 'P', '1', 'e', '5', 'h', 'K', 'f', 'G', 's', 'x', 'k', 'H', 'z', 'V', 'U', '.', 'j', 'p', 'g', "'", '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '2', 'c', 'e', 'c', '3', 'a', '3', '6', '8', '2', 'e', '8', '2', '0', '0', '0', '0', '2', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'C', 'r', 'e', 'w', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '1', '6', '2', '9', '4', '1', '9', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'P', 'o', 's', 't', '', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '', 'S', 'u', 'p', 'e', 'r', 'v', 'i', 's', 'o', 'r', "'", ',', '', "'", 'n', 'a', 'm', 'e', "'", ':', '', "'", 'P', 'a', 't', 's', 'y', '', 'B', 'o', 'u', 'g', 'e', "'", ',', '', "'", 'p', 'r', 'o', 'f', 'i', 'l', 'e', '_', 'p', 'a', 't', 'h', "'", ':', '', 'N', 'o', 'n', 'e', '}', ',', '', '{', "'", 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', "'", ':', '', "'", '5', '7', '4', 'f', '1', '4', 'f', '1', '9', '2', '5', '1', '4', '1', '5', 'c', 'a', '1', '0', '0', '0', '0', '8', '2', "'", ',', '', "'", 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', "'", ':', '', "'", 'A', 'r', 't', "'", ',', '', "'", 'g', 'e', 'n', 'd', 'e', 'r', "'", ':', '', '0', ',', '', "'", 'i', 'd', "'", ':', '', '7', '9', '6', '1', ',', '', "'", 'j', 'o', 'b', "'", ':', '', "'", 'S', 'c', 'u', 'l', 'p', 't', 'o', 'r', "'",

In [30]:
data=pd.read_csv('data_clean.csv')

In [31]:
data['crew'] = data['crew'].apply(ast.literal_eval)

In [33]:
print(type(data['crew'].iloc[0]))
print(type(data['crew'].iloc[0][0]))

<class 'list'>
<class 'dict'>

In [35]:
print(data['crew'].iloc[0])

JohnLasseter

In [37]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'cast_id': 14, 'character': 'Woody (voice)',...",JohnLasseter,http://toystory.disney.com/toy-story
1,710,GoldenEye,James Bond must unmask the mysterious head of ...,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","[{'cast_id': 1, 'character': 'James Bond', 'cr...",MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,Craig and Smokey are two guys in Los Angeles h...,"[{'id': 35, 'name': 'Comedy'}]","[{'cast_id': 1, 'character': 'Craig Jones', 'c...",F.GaryGray,http://www.newline.com/properties/friday.html

In [38]:
import ast

In [39]:
def genres(col):
    l=[]
    for i in ast.literal_eval(col):
        l.append(i['name']) 
    return l

In [40]:
data['genres']=data['genres'].apply(genres)

In [41]:
data['overview']=data['overview'].apply(lambda x:x.split())

In [46]:
data['genres'] = data['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [47]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[[, {, ', c, a, s, t, _, i, d, ', :, , 1, 4, ,...",JohnLasseter,http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]","[[, {, ', c, a, s, t, _, i, d, ', :, , 1, ,, ,...",MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],"[[, {, ', c, a, s, t, _, i, d, ', :, , 1, ,, ,...",F.GaryGray,http://www.newline.com/properties/friday.html

In [48]:
data['cast']=data['cast'].dropna()

In [49]:
data.head(3)

,id,title,overview,genres,cast,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[[, {, ', c, a, s, t, _, i, d, ', :, , 1, 4, ,...",JohnLasseter,http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]","[[, {, ', c, a, s, t, _, i, d, ', :, , 1, ,, ,...",MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],"[[, {, ', c, a, s, t, _, i, d, ', :, , 1, ,, ,...",F.GaryGray,http://www.newline.com/properties/friday.html

In [50]:
data.drop('cast', axis=1, inplace=True)

In [51]:
data.head(3)

,id,title,overview,genres,crew,homepage
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]",JohnLasseter,http://toystory.disney.com/toy-story
1,710,GoldenEye,"[James, Bond, must, unmask, the, mysterious, h...","[Adventure, Action, Thriller]",MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/
2,10634,Friday,"[Craig, and, Smokey, are, two, guys, in, Los, ...",[Comedy],F.GaryGray,http://www.newline.com/properties/friday.html

In [55]:
data['tags']=data['overview']+data['genres']

In [58]:
data.drop(['overview', 'genres'], axis=1, inplace=True)

In [59]:
data.head(3)

,id,title,crew,homepage,tags
0,862,Toy Story,JohnLasseter,http://toystory.disney.com/toy-story,"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,710,GoldenEye,MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/,"[James, Bond, must, unmask, the, mysterious, h..."
2,10634,Friday,F.GaryGray,http://www.newline.com/properties/friday.html,"[Craig, and, Smokey, are, two, guys, in, Los, ..."

In [70]:
data.head(3)

,id,title,crew,homepage,tags
0,862,Toy Story,JohnLasseter,http://toystory.disney.com/toy-story,"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,710,GoldenEye,MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/,"[James, Bond, must, unmask, the, mysterious, h..."
2,10634,Friday,F.GaryGray,http://www.newline.com/properties/friday.html,"[Craig, and, Smokey, are, two, guys, in, Los, ..."

In [71]:
data.to_csv('workdata_clean.csv', index=False)

In [72]:
pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Collecting defusedxml (from nltk)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting click (from nltk)
  Using cached click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from nltk) (1.6.0)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.10-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python314\site-packages (from tqdm->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 12.3 MB/s  0:00:00
Downloading regex-2026.9.10-cp314-cp314-win_amd64.whl (281 kB)
Using cached click-8.5.0-py3-none-any.whl (125 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, regex, defusedxml, click, nltk

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [regex]
   -------- ------------------------------- 1/5 [regex]
   ---------------- ----------------------- 2/5 [defusedxml]
   ---------------- ----------------------- 2/5 [defusedxml]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   ---------------------------------------- 5/5 [nltk]

Successfully installed click-8.5.0 defusedxml-0.7.1 nltk-3.10.3 regex-2026.9.10 tqdm-4.70.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tqdm.exe is installed in 'c:\Users\user\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk.exe is installed in 'c:\Users\user\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
from nltk.stem.porter import PorterStemmer

In [74]:
ps=PorterStemmer()

In [77]:
def stemmer(text):
    l=[]
    for i in text:
        l.append(ps.stem(i))
    return " ".join(l)

In [78]:
data['tags']=data['tags'].apply(stemmer)

In [79]:
data.head(3)

,id,title,crew,homepage,tags
0,862,Toy Story,JohnLasseter,http://toystory.disney.com/toy-story,"led by woody, andy' toy live happili in hi roo..."
1,710,GoldenEye,MartinCampbell,http://www.mgm.com/view/movie/757/Goldeneye/,jame bond must unmask the mysteri head of the ...
2,10634,Friday,F.GaryGray,http://www.newline.com/properties/friday.html,craig and smokey are two guy in lo angel hang ...

In [80]:
data['tags'][0]

"led by woody, andy' toy live happili in hi room until andy' birthday bring buzz lightyear onto the scene. afraid of lose hi place in andy' heart, woodi plot against buzz. but when circumst separ buzz and woodi from their owner, the duo eventu learn to put asid their differences. anim comedi famili"

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [82]:
tfidf=TfidfVectorizer(max_features=5000, stop_words='english')

In [85]:
vectors=tfidf.fit_transform(data['tags']).toarray()

In [86]:
print(vectors.shape)

(980, 5000)

In [92]:
tfidf.get_feature_names_out()[:200]

array(['00', '000', '007', '009', '01', '10', '100', '1000', '108',
       '10crores', '11', '117', '11th', '12', '12th', '13', '13th', '14',
       '15', '150', '16', '17', '18', '1923', '1955', '1957', '1969',
       '1980s', '1983', '1985', '1986', '1988', '1990', '1994', '1996',
       '1997', '1998', '1999', '20', '200', '2001', '2006', '2007',
       '2008', '2009', '2010', '2011', '2019', '2028', '21st', '22nd',
       '23', '24', '25', '250', '26', '30', '300', '35', '3d', '3po',
       '42', '47', '49', '4th', '50', '501st', '60', '70', '80', '95',
       'aaron', 'abandon', 'abduct', 'abigail', 'abil', 'abl', 'aboard',
       'absolut', 'absorb', 'abus', 'academ', 'academi', 'academy',
       'accept', 'accid', 'accident', 'accompani', 'accomplish', 'accord',
       'account', 'accus', 'accused', 'acerola', 'achiev', 'acquir',
       'act', 'action', 'activ', 'activist', 'actor', 'actress', 'actual',
       'adapt', 'add', 'addict', 'addit', 'address', 'adjust',
       'administr', 'adopt', 'ador', 'adrenaline', 'adult', 'adulthood',
       'advanc', 'advantag', 'adventur', 'adventure', 'adversari',
       'advic', 'affair', 'affect', 'afflict', 'afghanistan', 'afraid',
       'africa', 'afro', 'aftermath', 'afternoon', 'ag', 'age', 'agenc',
       'agency', 'agent', 'agents', 'ago', 'agre', 'ahead', 'aid', 'aiko',
       'aim', 'ain', 'air', 'airport', 'akan', 'akko', 'al', 'aladdin',
       'alaska', 'alaskan', 'albeit', 'albright', 'alcohol', 'alcoholic',
       'alejandro', 'alert', 'alesia', 'alex', 'ali', 'alic', 'alice',
       'alien', 'aliens', 'alik', 'aliv', 'alive', 'alla', 'alley',
       'alli', 'allianc', 'allies', 'allow', 'alon', 'alongsid', 'alpha',
       'alphons', 'alreadi', 'alter', 'altern', 'alto', 'alvin', 'alway',
       'amanda', 'amaz', 'amazon', 'ambassador', 'ambiti', 'ambush',
       'america', 'american', 'ami', 'amidst', 'amnesia', 'amp', 'ana',
       'anakin', 'analyst', 'ancient', 'anderson'], dtype=object)

In [93]:
from sklearn.metrics.pairwise import cosine_similarity

In [94]:
similarity=cosine_similarity(vectors)

In [95]:
vectors.shape

(980, 5000)

In [100]:
similarity[1]

array([0.        , 1.        , 0.        , 0.01619748, 0.        ,
       0.0139851 , 0.        , 0.01149885, 0.        , 0.        ,
       0.00624939, 0.01185709, 0.        , 0.02080831, 0.02659045,
       0.07121102, 0.03248057, 0.        , 0.        , 0.05894962,
       0.        , 0.        , 0.00848248, 0.01419717, 0.00808744,
       0.        , 0.04635002, 0.00558465, 0.        , 0.04418906,
       0.01657941, 0.        , 0.03914397, 0.01267721, 0.0068141 ,
       0.0132504 , 0.00654793, 0.        , 0.01420878, 0.06313466,
       0.02000569, 0.07286251, 0.04463423, 0.        , 0.07954542,
       0.01307018, 0.00789907, 0.00967539, 0.03110239, 0.00692686,
       0.        , 0.01201672, 0.00679637, 0.0113747 , 0.04675509,
       0.01648664, 0.00436771, 0.02456523, 0.02196782, 0.12169103,
       0.01505488, 0.00707295, 0.01310643, 0.08085448, 0.        ,
       0.00632274, 0.02066035, 0.        , 0.11353456, 0.07706156,
       0.1247252 , 0.13680788, 0.03254849, 0.11013673, 0.18627466,
       0.17926464, 0.10756225, 0.03329163, 0.07796017, 0.01904055,
       0.        , 0.        , 0.01853876, 0.01179034, 0.02240432,
       0.        , 0.01470573, 0.05864983, 0.1161571 , 0.10385909,
       0.07201348, 0.10562776, 0.01704594, 0.00654444, 0.01695086,
       0.02249953, 0.        , 0.        , 0.14370172, 0.11488414,
       0.        , 0.02203606, 0.00776287, 0.        , 0.06125234,
       0.        , 0.00393559, 0.01313104, 0.06563995, 0.0067596 ,
       0.00910448, 0.02818885, 0.01692843, 0.00754816, 0.00698213,
       0.00548502, 0.04818907, 0.06282488, 0.00858232, 0.0077947 ,
       0.04617434, 0.02764907, 0.00831825, 0.        , 0.02719569,
       0.0126633 , 0.00942621, 0.        , 0.13249236, 0.01859206,
       0.01445691, 0.        , 0.03288231, 0.        , 0.00695114,
       0.04123   , 0.01200115, 0.01650528, 0.01370198, 0.00808001,
       0.00732935, 0.        , 0.        , 0.039651  , 0.01423844,
       0.05083133, 0.00525597, 0.        , 0.01111365, 0.16884185,
       0.20329526, 0.14935612, 0.        , 0.00556511, 0.012334  ,
       0.        , 0.        , 0.01491303, 0.01620004, 0.03498658,
       0.01178036, 0.01880863, 0.        , 0.        , 0.        ,
       0.02309884, 0.        , 0.00688554, 0.        , 0.        ,
       0.        , 0.        , 0.02850126, 0.02182385, 0.01912553,
       0.        , 0.01637827, 0.04055099, 0.00769135, 0.00630983,
       0.        , 0.01047916, 0.        , 0.02712391, 0.02928853,
       0.02388708, 0.00919695, 0.        , 0.00676433, 0.05981475,
       0.0227593 , 0.01264401, 0.04788853, 0.        , 0.01753439,
       0.00884199, 0.03895123, 0.00717278, 0.        , 0.0092933 ,
       0.02612745, 0.03209154, 0.02797987, 0.00602066, 0.01995724,
       0.        , 0.0572223 , 0.06051864, 0.00752273, 0.02920109,
       0.01252533, 0.06837417, 0.00857439, 0.09512846, 0.        ,
       0.02181206, 0.        , 0.        , 0.        , 0.        ,
       0.01806512, 0.04906199, 0.        , 0.00330279, 0.02039266,
       0.01116087, 0.00475735, 0.01319203, 0.        , 0.01232885,
       0.01281187, 0.0122136 , 0.        , 0.        , 0.0074719 ,
       0.07174556, 0.03552528, 0.00897535, 0.00845976, 0.        ,
       0.0200505 , 0.03516661, 0.        , 0.01390058, 0.02083282,
       0.02786751, 0.        , 0.        , 0.00528003, 0.01715792,
       0.00819273, 0.0162367 , 0.00874788, 0.00691109, 0.005595  ,
       0.        , 0.01964575, 0.01915476, 0.0555157 , 0.04117873,
       0.0113739 , 0.021864  , 0.02013053, 0.        , 0.03915867,
       0.04865987, 0.01269586, 0.0267369 , 0.        , 0.01300745,
       0.00505814, 0.02907253, 0.        , 0.07424098, 0.03638579,
       0.        , 0.00713943, 0.01426999, 0.        , 0.00951084,
       0.        , 0.        , 0.        , 0.        , 0.01252455,
       0.00850665, 0.        , 0.01491573, 0.01813381, 0.        ,
       0.11646894, 0.        , 0.02048868, 0.02244897, 0.        ,
       0.        , 0.        , 0.        , 0.03022054, 0.00458382,
       0.00645993, 0.01508212, 0.01201493, 0.00917453, 0.02908164,
       0.        , 0.        , 0.01572285, 0.01063369, 0.02282906,
       0.02512744, 0.01381777, 0.02264511, 0.09739307, 0.01142734,
       0.02106535, 0.04709202, 0.01405613, 0.02207344, 0.01780589,
       0.        , 0.        , 0.01869399, 0.0080486 , 0.0120285 ,
       0.01635791, 0.00967012, 0.01162469, 0.08506835, 0.05389996,
       0.0149088 , 0.        , 0.        , 0.03706828, 0.02350357,
       0.        , 0.01824529, 0.01481151, 0.01769888, 0.0067276 ,
       0.        , 0.        , 0.        , 0.01786919, 0.03540172,
       0.        , 0.05560987, 0.00788169, 0.        , 0.01063306,
       0.02686572, 0.        , 0.        , 0.01931551, 0.        ,
       0.02222526, 0.00611208, 0.        , 0.        , 0.00894034,
       0.04512006, 0.        , 0.01076698, 0.00854175, 0.        ,
       0.02914067, 0.        , 0.04377013, 0.02721042, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00630418,
       0.        , 0.01838613, 0.        , 0.        , 0.        ,
       0.00306602, 0.05943001, 0.        , 0.00929501, 0.        ,
       0.09344224, 0.        , 0.        , 0.        , 0.00941346,
       0.03625037, 0.        , 0.        , 0.0070885 , 0.        ,
       0.01320134, 0.00984724, 0.        , 0.00750603, 0.0142406 ,
       0.00773523, 0.        , 0.05633972, 0.02864175, 0.        ,
       0.        , 0.        , 0.        , 0.01122406, 0.06564925,
       0.00785388, 0.        , 0.01767921, 0.        , 0.        ,
       0.0134263 , 0.05311183, 0.0045847 , 0.00623098, 0.00876531,
       0.01322282, 0.03388796, 0.04832853, 0.00983339, 0.01581218,
       0.00998086, 0.00910743, 0.01167452, 0.03103566, 0.01320813,
       0.02220208, 0.01802795, 0.03377268, 0.        , 0.        ,
       0.05097919, 0.01416868, 0.01022949, 0.        , 0.01346956,
       0.        , 0.04407504, 0.        , 0.00757493, 0.087857  ,
       0.        , 0.00673628, 0.        , 0.00301462, 0.04223927,
       0.        , 0.01555876, 0.02859527, 0.01346005, 0.00893151,
       0.00931866, 0.        , 0.02190735, 0.01431568, 0.        ,
       0.        , 0.        , 0.01393896, 0.04185755, 0.07080495,
       0.        , 0.00448465, 0.        , 0.09009913, 0.        ,
       0.00541492, 0.        , 0.01880079, 0.        , 0.09285319,
       0.00473013, 0.05079101, 0.03431325, 0.03822106, 0.0166129 ,
       0.        , 0.00486986, 0.        , 0.01941385, 0.00669014,
       0.0113071 , 0.01195494, 0.01706742, 0.02002725, 0.        ,
       0.02774037, 0.01826908, 0.00439765, 0.        , 0.00515274,
       0.04958273, 0.02703137, 0.03621356, 0.0058248 , 0.02308105,
       0.00965821, 0.        , 0.        , 0.        , 0.01292729,
       0.05777138, 0.        , 0.00464315, 0.00483278, 0.03022397,
       0.03519683, 0.        , 0.        , 0.01759138, 0.01942594,
       0.08182823, 0.        , 0.0139529 , 0.        , 0.        ,
       0.01308141, 0.        , 0.01337855, 0.02198506, 0.        ,
       0.        , 0.00928307, 0.01578808, 0.        , 0.01952639,
       0.00505554, 0.00362065, 0.00532891, 0.00487382, 0.        ,
       0.01560864, 0.        , 0.00628399, 0.        , 0.        ,
       0.        , 0.00343319, 0.        , 0.01613121, 0.        ,
       0.00414858, 0.00414858, 0.00675397, 0.02463326, 0.04798246,
       0.04285699, 0.03087813, 0.03267468, 0.04633369, 0.00371026,
       0.02501732, 0.01454938, 0.00761909, 0.05257482, 0.01904858,
       0.02007866, 0.01897303, 0.        , 0.0177887 , 0.01790088,
       0.        , 0.02331478, 0.03127404, 0.01089048, 0.02330033,
       0.        , 0.        , 0.01132326, 0.01135278, 0.        ,
       0.02040515, 0.02324633, 0.00525517, 0.00977152, 0.        ,
       0.        , 0.01729398, 0.        , 0.        , 0.        ,
       0.01210823, 0.03868728, 0.        , 0.04103451, 0.        ,
       0.00534853, 0.0130778 , 0.01131742, 0.00998596, 0.00920553,
       0.00881975, 0.01445967, 0.        , 0.        , 0.03489041,
       0.        , 0.00353592, 0.        , 0.03194204, 0.        ,
       0.        , 0.02480802, 0.00910859, 0.0033873 , 0.02317533,
       0.01260135, 0.        , 0.0074307 , 0.00837795, 0.09133125,
       0.00990547, 0.        , 0.00716064, 0.04710561, 0.0100261 ,
       0.        , 0.01779395, 0.        , 0.12669449, 0.00573867,
       0.05106173, 0.0045204 , 0.02449156, 0.        , 0.01192357,
       0.00603505, 0.01835133, 0.01908619, 0.01186659, 0.        ,
       0.01010051, 0.01815386, 0.02567125, 0.01166176, 0.03877351,
       0.01185195, 0.        , 0.02399022, 0.        , 0.00987069,
       0.00739281, 0.        , 0.        , 0.00925493, 0.00991308,
       0.        , 0.02883083, 0.        , 0.        , 0.05985305,
       0.01087255, 0.01712295, 0.02432505, 0.00809456, 0.0186817 ,
       0.0036891 , 0.00545863, 0.00963761, 0.01631784, 0.02110882,
       0.01681195, 0.07023551, 0.        , 0.        , 0.        ,
       0.00680523, 0.00408561, 0.        , 0.02538138, 0.02712898,
       0.01806575, 0.01649365, 0.04047374, 0.01030677, 0.0136078 ,
       0.01025921, 0.01059687, 0.01692491, 0.04873073, 0.01397413,
       0.        , 0.        , 0.0089055 , 0.00695634, 0.00663371,
       0.00854941, 0.        , 0.02012696, 0.00689375, 0.        ,
       0.01956074, 0.00890155, 0.        , 0.        , 0.02562423,
       0.02520162, 0.00714714, 0.00827986, 0.        , 0.        ,
       0.09499421, 0.        , 0.        , 0.09556287, 0.        ,
       0.01170706, 0.01533567, 0.00956446, 0.01874346, 0.01024307,
       0.01751167, 0.00518403, 0.00593211, 0.00612128, 0.        ,
       0.07855454, 0.04183434, 0.        , 0.01119297, 0.00767152,
       0.        , 0.00925367, 0.02995608, 0.0058553 , 0.0038109 ,
       0.        , 0.        , 0.01027241, 0.01223438, 0.01361553,
       0.03778406, 0.00683909, 0.00892594, 0.0100585 , 0.08704036,
       0.00585919, 0.05620574, 0.01255897, 0.        , 0.        ,
       0.        , 0.04144437, 0.03867799, 0.00611606, 0.00432617,
       0.01971001, 0.0229057 , 0.        , 0.        , 0.01069906,
       0.01201613, 0.06066563, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00912502, 0.01491086,
       0.        , 0.00610846, 0.0037016 , 0.00271665, 0.        ,
       0.        , 0.        , 0.        , 0.00611391, 0.0220739 ,
       0.00486483, 0.00476091, 0.        , 0.01047613, 0.00252476,
       0.00961567, 0.00895513, 0.        , 0.02655979, 0.01157706,
       0.02123408, 0.        , 0.00388146, 0.03785995, 0.0077947 ,
       0.05534173, 0.02550545, 0.07370045, 0.        , 0.        ,
       0.        , 0.        , 0.02533084, 0.0138913 , 0.01654924,
       0.05139471, 0.        , 0.04325146, 0.        , 0.        ,
       0.00816848, 0.        , 0.0222224 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04664184, 0.01125606,
       0.        , 0.03154354, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01146074, 0.01101472, 0.02594783,
       0.09274598, 0.01102401, 0.01345062, 0.0077551 , 0.02447896,
       0.00996108, 0.        , 0.00706684, 0.01090576, 0.00795908,
       0.        , 0.00513226, 0.        , 0.01604061, 0.        ,
       0.        , 0.        , 0.05823728, 0.02132147, 0.01128508,
       0.01090864, 0.01241076, 0.04936036, 0.        , 0.00754693,
       0.01027838, 0.        , 0.0097421 , 0.        , 0.        ,
       0.00534274, 0.04866883, 0.01262775, 0.00539569, 0.00959273,
       0.        , 0.00696039, 0.01828606, 0.02966776, 0.03394767,
       0.01204598, 0.00894769, 0.02730258, 0.0072143 , 0.        ,
       0.00912835, 0.        , 0.        , 0.        , 0.        ,
       0.01543965, 0.00477307, 0.00335745, 0.00302437, 0.0149908 ,
       0.01459749, 0.03231665, 0.02407393, 0.        , 0.        ,
       0.        , 0.0064427 , 0.        , 0.0188735 , 0.01498489,
       0.0199948 , 0.02071877, 0.04693614, 0.00816707, 0.01285291,
       0.        , 0.        , 0.01727972, 0.        , 0.00876999,
       0.        , 0.0107113 , 0.01497927, 0.        , 0.00709742,
       0.        , 0.        , 0.01439925, 0.01076189, 0.        ,
       0.02078792, 0.01094022, 0.01713464, 0.00637986, 0.00896962,
       0.        , 0.01355963, 0.01212006, 0.03418067, 0.01285281,
       0.01095305, 0.01461747, 0.01039825, 0.        , 0.00851661,
       0.        , 0.02119927, 0.0058074 , 0.        , 0.        ,
       0.00577151, 0.        , 0.04336289, 0.00441585, 0.03486369,
       0.01525825, 0.01265095, 0.01507936, 0.01634519, 0.00600368,
       0.        , 0.03729259, 0.        , 0.01553079, 0.03157355,
       0.        , 0.01091963, 0.00749236, 0.        , 0.        ,
       0.00912095, 0.        , 0.04874404, 0.00551375, 0.00685606,
       0.03120851, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04366366, 0.01840571, 0.        ,
       0.        , 0.        , 0.0048516 , 0.02046743, 0.        ,
       0.01179022, 0.04192228, 0.        , 0.00811825, 0.0117045 ,
       0.01493337, 0.        , 0.03034606, 0.01264996, 0.00786948])

In [111]:
def recommend(movie):
    movie_index = data[data["title"] == movie].index[0]

    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movie_list:
        print(data.iloc[i[0]]["title"])
        print("Homepage:", data.iloc[i[0]]["homepage"])

In [112]:
recommend("Toy Story")

Toy Story 3
Homepage: http://disney.go.com/toystory/
Toy Story 2
Homepage: http://toystory.disney.com/toy-story-2
Harry Potter and the Philosopher's Stone
Homepage: http://harrypotter.warnerbros.com/harrypotterandthedeathlyhallows/mainsite/index.html
Monsters, Inc.
Homepage: http://movies.disney.com/monsters-inc
A Close Shave
Homepage: http://www.wallaceandgromit.com/films/a-close-shave

In [113]:
recommend("GoldenEye")

Octopussy
Homepage: http://www.mgm.com/view/movie/1394/Octopussy/
Licence to Kill
Homepage: http://www.mgm.com/view/movie/1111/License-to-Kill/
Live and Let Die
Homepage: http://www.mgm.com/view/movie/1130/Live-and-Let-Die/
You Only Live Twice
Homepage: http://www.mgm.com/view/movie/2347/You-Only-Live-Twice/
Never Say Never Again
Homepage: http://www.mgm.com/view/movie/1345/Never-Say-Never-Again/